name: CI

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  PHP_CS_FIXER_IGNORE_ENV: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  pest:
    name: Pest (P${{ matrix.php }} - L${{ matrix.laravel }})

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - laravel: 9
            php: "8.0"
          - laravel: 10
            php: "8.2"
          - laravel: 11
            php: "8.3"
          - laravel: 12
            php: "8.4"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install composer dependencies
        run: composer require "illuminate/support:^${{ matrix.laravel }}"

      - name: Run tests
        run: vendor/bin/pest

  phpstan:
    name: Static analysis (PHPStan) – (${{ matrix.php }} - L${{ matrix.laravel }})

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - laravel: 9
            php: "8.0"
          - laravel: 10
            php: "8.2"
          - laravel: 11
            php: "8.3"
          - laravel: 12
            php: "8.4"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install composer dependencies
        run: composer install

      - name: Run phpstan
        run: vendor/bin/phpstan analyse
